const array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
console.log(array);
array.push("Apple");
array.push("Banana");
array.push("Mango");
console.log(array);
array.pop();
console.log(array);
array.unshift("Ram");
array.unshift("Shyam");
array.unshift("Hari");
console.log(array);
array.shift();
console.log(array);